imports:
    - { resource: parameters.yml }
    - { resource: parameters_ldap.yml }
    - { resource: parameters_celcat.yml }
    - { resource: parameters_mail.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [CelcatManagementAppBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
    assets:
        glyphicons-halflings-regular-eot:
            inputs: '%kernel.root_dir%/Resources/public/fonts/glyphicons-halflings-regular.eot'
            output: 'fonts/glyphicons-halflings-regular.eot'
        glyphicons-halflings-regular-svg:
            inputs: '%kernel.root_dir%/Resources/public/fonts/glyphicons-halflings-regular.svg'
            output: 'fonts/glyphicons-halflings-regular.svg'
        glyphicons-halflings-regular-ttf:
            inputs: '%kernel.root_dir%/Resources/public/fonts/glyphicons-halflings-regular.ttf'
            output: 'fonts/glyphicons-halflings-regular.ttf'
        glyphicons-halflings-regular-woff:
            inputs: '%kernel.root_dir%/Resources/public/fonts/glyphicons-halflings-regular.woff'
            output: 'fonts/glyphicons-halflings-regular.woff'
        glyphicons-halflings-regular-woff2:
            inputs: '%kernel.root_dir%/Resources/public/fonts/glyphicons-halflings-regular.woff2'
            output: 'fonts/glyphicons-halflings-regular.woff2'
# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
    
    
mopa_bootstrap:
    form: 
        show_legend: false
        collection:
            widget_remove_btn:
                icon: trash
                label: Supprimer
            widget_add_btn:
                icon: plus-sign
                label: Ajouter
        render_required_asterisk: true
        render_optional_text: false
        tabs:
            class: 'nav nav-tabs ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all'

be_simple_sso_auth:
    admin_sso:
        protocol:
            id: cas
            version: 2
        server:
            id: cas
            login_url: https://cas.univ-angers.fr/cas/login
            logout_url: https://cas.univ-angers.fr/cas/logout
            validation_url: https://cas.univ-angers.fr/cas/serviceValidate

genemu_form:
    select2: ~
    
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: Pagination/twitter_bootstrap_v3_pagination.html.twig     # sliding pagination controls template
        sortable: Pagination/sortable_link.html.twig # sort link template