celcat_management_ldap_manager:
    resource: "@CelcatManagementLDAPManagerBundle/Resources/config/routing.yml"
    prefix:   /LDAP

celcat_management_celcat_reader:
    resource: "@CelcatManagementCelcatReaderBundle/Resources/config/routing.yml"
    prefix:   /CELCAT

celcat_management_app:
    resource: "@CelcatManagementAppBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
fullcalendar_loader:
    pattern: /fc-load-calendar-events
    defaults: { _controller: CelcatManagementAppBundle:Calendar:loadCalendar }
    options:
        expose: true
        
event_calendar_loader:
    pattern: /fc-load-calendar-events-by-id
    defaults: { _controller: CelcatManagementAppBundle:Calendar:loadEventCalendar }
    options:
        expose: true