services:
    user_provider_service:
        class: CelcatManagement\AppBundle\Entity\UserProvider
        arguments: [{ROLE_USER, ROLE_ADMIN}]
#    celcat_management_app.example:
#        class: CelcatManagement\AppBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
