CelcatManagement\AppBundle\Entity\EventModification:
    type: entity
    table: event_modification
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        eventId:
            type: string
            length: 20
            column: event_id
        eventTitre:
            type: string
            length: 50
            column: event_titre
        professors:
            type: array
        groupes:
            type: array
        startDateTimeInitial:
            type: date
            column: start_datetime_initial
        endDateTimeInitial:
            type: date
            column: end_datetime_initial
        startDateTimeFinal:
            type: date
            column: start_datetime_final
        endDateTimeFinal:
            type: date
            column: end_datetime_final
        
        
    lifecycleCallbacks: {  }
