CelcatManagement\AppBundle\Entity\ScheduleModification:
    type: entity
    table: schedule_modification
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        user:
            type: string
            length: 20
            column: user
        canceled:
            type: boolean
        validated:
            type: boolean
    oneToOne:
        firstEvent:
            targetEntity: EventModification
            joinColumn:
                name: id_first_event
                referencedColumnName: id
            nullable: false
            cascade: [persist]
        secondEvent:
            targetEntity: EventModification
            joinColumn:
                name: id_second_event
                referencedColumnName: id
            nullable: true
            cascade: [persist]
    lifecycleCallbacks: {  }
