CelcatManagement\AppBundle\Entity\UserMail:
    type: entity
    table: user_mail
    
    fields:
        sendDate:
            type: datetime
            version: true
            column: send_date
    lifecycleCallbacks: {  }
