CelcatManagement\AppBundle\Entity\UserMail:
    type: entity
    table: user_mail
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        sended:
            type: boolean
        sendDate:
            type: datetime
            version: true
            column: send_date
    lifecycleCallbacks: {  }
