login:
    pattern: /login
    defaults: { _controller: CelcatManagementAppBundle:Login:login }
logout:
    pattern: /logout
login_check:
    pattern: /login_check
    defaults: { _controller: CelcatManagementAppBundle:Login:login }
    
profil:
    pattern: /profil
    defaults: {_controller: CelcatManagementAppBundle:Login:profil }
    
celcat_management_app_login_edit:
    path:     /profil/edit
    defaults: { _controller: "CelcatManagementAppBundle:Login:edit" }

celcat_management_app_login_update:
    path:     /profil/update
    defaults: { _controller: "CelcatManagementAppBundle:Login:update" }
    methods:  [POST, PUT]