celcat_management_app_mailer:
    pattern: /
    defaults: {_controller: CelcatManagementAppBundle:Mailer:index }
    
celcat_management_app_mailer_send:
    pattern: /send
    defaults: {_controller: CelcatManagementAppBundle:Mailer:send }
    
celcat_management_app_mailer_sendmodification:
    pattern: /sendmodification
    defaults: {_controller: CelcatManagementAppBundle:Mailer:sendModification }
    
celcat_management_app_mailer_send_unsend:
    pattern: /send_unsend
    defaults: {_controller: CelcatManagementAppBundle:Mailer:sendUnsendedMail }