celcat_management_app_schedulemodification:
    path:     /
    defaults: { _controller: "CelcatManagementAppBundle:ScheduleModification:index" }

celcat_management_app_schedulemodification_show:
    path:     /{id}/show
    defaults: { _controller: "CelcatManagementAppBundle:ScheduleModification:show" }

celcat_management_app_schedulemodification_new:
    path:     /new
    defaults: { _controller: "CelcatManagementAppBundle:ScheduleModification:new" }

celcat_management_app_schedulemodification_create:
    path:     /create
    defaults: { _controller: "CelcatManagementAppBundle:ScheduleModification:create" }
    methods:  POST

celcat_management_app_schedulemodification_create_from_schedule_manager:
    path:     /create-from-schedule
    defaults: { _controller: "CelcatManagementAppBundle:ScheduleModification:createFromScheduleManager" }

celcat_management_app_schedulemodification_edit:
    path:     /{id}/edit
    defaults: { _controller: "CelcatManagementAppBundle:ScheduleModification:edit" }

celcat_management_app_schedulemodification_update:
    path:     /{id}/update
    defaults: { _controller: "CelcatManagementAppBundle:ScheduleModification:update" }
    methods:  [POST, PUT]

celcat_management_app_schedulemodification_delete:
    path:     /{id}/delete
    defaults: { _controller: "CelcatManagementAppBundle:ScheduleModification:delete" }
    methods:  [GET, POST, DELETE]
    
celcat_management_app_schedulemodification_send_mail:
    path:     /mail
    defaults: { _controller: "CelcatManagementAppBundle:ScheduleModification:sendModificationMail" }

celcat_management_app_schedulemodification_send_ask_mail:
    path:     /mail_ask
    defaults: { _controller: "CelcatManagementAppBundle:ScheduleModification:sendAskMail" }
    
celcat_management_app_schedulemodification_send_validation_mail:
    path:     /mail_validation
    defaults: { _controller: "CelcatManagementAppBundle:ScheduleModification:sendValidationMail" }
    
celcat_management_app_schedulemodification_validation_needed:
    path:   /validation
    defaults:   { _controller: "CelcatManagementAppBundle:ScheduleModification:waitingValidation" }
    
celcat_management_app_schedulemodification_validate:
    path:   /validation/{id}
    defaults:   { _controller: "CelcatManagementAppBundle:ScheduleModification:validate" }