celcat_management_ldap_manager_homepage:
    path:     /hello/{name}
    defaults: { _controller: CelcatManagementLDAPManagerBundle:Default:index }

celcat_management_ldap_manager_index:
    path:     /
    defaults: { _controller: CelcatManagementLDAPManagerBundle:Default:index }
